name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7, 3.8, 3.9, '3.10', '3.11']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install -r requirements-dev.txt
    - name: Temporary installation
      run: python -m pip install -e .
    - name: Test with pytest
      run: |
        pytest
    - name: Check types with mypy
      run: |
        mypy docstring_to_markdown
    - name: Build package
      run: |
        python setup.py sdist bdist_wheel
    - name: Install package
      run: python -m pip install --find-links=dist --no-index --ignore-installed docstring_to_markdown
    - name: Pip check
      run: python -m pip check
